### ISSUE TITLE
add purego option

### ISSUE THREAD

**Issue by MatejMagat305** [goki/vgpu#10]
Well I know, I know it is lot of work add something new, but it would be nice add option with https://github.com/ebitengine/purego - call C without cgo (without gcc ...) it is slower, but it is usefull maybe with https://github.com/JupiterRider/ffi

**Comment by kkoreilly** [comment]
Yep, I thought about this previously, and it would definitely be good to do this at some point. Development of vgpu is now taking place in https://github.com/cogentcore/core, so I will create an issue for this there instead.
