### ISSUE TITLE
Version 1.0.25 causes panic on old MacBooks due to use of ShaderInt64

### ISSUE THREAD

**Issue by kkoreilly** [goki/vgpu#3]
Physical Device Feature 41 (ShaderInt64) is not available on old MacBooks (mine is from early 2016). The use of it causes a panic with vulkan error: feature not present.

**Comment by gedw99** [comment]
Ah same here on my 2013 macbook :)

**Comment by rcoreilly** [comment]
v1.0.27 just released includes full PhysicalDeviceFeatures options support (see CPUOpts in opts.go) and ShaderInt64 is no longer enabled by default.
